import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of, catchError } from 'rxjs';
import { AppConfigService } from './app-config.service';

export type SqlDialect = 'postgres' | 'mysql' | 'sqlserver' | 'sqlite' | 'oracle' | 'mongodb';

export interface ExportRequest {
  databaseType: string;
  dbmlScript: string;
}

@Injectable({
  providedIn: 'root'
})
export class ExportService {

  private readonly databaseTypeMap: Record<SqlDialect, string> = {
    postgres: 'Postgres',
    mysql: 'Mysql',
    sqlserver: 'SqlServer',
    sqlite: 'Sqlite',
    oracle: 'Oracle',
    mongodb: 'MongoDB'
  };

  constructor(private http: HttpClient, private appConfig: AppConfigService) {}

  
  convert(diagramId: string | number, dialect: SqlDialect, dbmlScript: string): Observable<string> {
    const url = this.appConfig.environment?.importExportApiUrls?.export?.replace('{id}', diagramId.toString()) ?? '';

    const body: ExportRequest = {
      databaseType: this.databaseTypeMap[dialect] || 'Postgres',
      dbmlScript
    };

    if (dialect === 'mongodb') {
      return this.http.post(url, body, { responseType: 'text' }).pipe(
        catchError(() => of(this.generateMongooseModels(dbmlScript)))
      );
    }

    return this.http.post(url, body, { responseType: 'text' });
  }

  downloadSqlFile(sql: string, dialect: SqlDialect): void {
    if (typeof window === 'undefined') return;
    const isMongo = dialect === 'mongodb';
    let ext = 'sql';
    let mime = 'text/plain;';
    let content = sql;

    if (isMongo) {
      const trimmed = sql.trim();
      const isJson = trimmed.startsWith('{') || trimmed.startsWith('[');
      if (isJson) {
        ext = 'json';
        mime = 'application/json';
        try {
          content = JSON.stringify(JSON.parse(trimmed), null, 2);
        } catch {
          content = sql;
        }
      } else {
        ext = 'js';
        mime = 'text/javascript';
      }
    }

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `schema_${dialect}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Internal converter to generate Mongoose schema models from DBML
   */
  private generateMongooseModels(dbml: string): string {
    const tableRegex = /Table\s+(?:["']?([A-Za-z0-9_.]+)["']?)\s*(?:as\s+\w+\s*)?\{([\s\S]*?)\}/gi;
    const refRegex = /Ref(?:\s+[A-Za-z0-9_]+)?\s*:\s*"?([A-Za-z0-9_]+)"?\."?([A-Za-z0-9_]+)"?\s*(?:>|<|-|<->)\s*"?([A-Za-z0-9_]+)"?\."?([A-Za-z0-9_]+)"?/gi;

    const refs: { fromTable: string; fromCol: string; toTable: string; toCol: string }[] = [];
    let refMatch: RegExpExecArray | null;
    while ((refMatch = refRegex.exec(dbml)) !== null) {
      refs.push({ fromTable: refMatch[1], fromCol: refMatch[2], toTable: refMatch[3], toCol: refMatch[4] });
    }

    let code = `// Mongoose Models Generated by SchemaFlow\nconst mongoose = require('mongoose');\nconst { Schema } = mongoose;\n\n`;
    const modelNames: string[] = [];

    let match: RegExpExecArray | null;
    while ((match = tableRegex.exec(dbml)) !== null) {
      const tableName = match[1].replace(/.*[.]/, '');
      const body = match[2];
      const modelName = tableName.charAt(0).toUpperCase() + tableName.slice(1).replace(/s$/, '');
      modelNames.push(modelName);

      code += `// Collection: ${tableName}\nconst ${modelName}Schema = new Schema({\n`;
      const fieldLines: string[] = [];

      body.split('\n').forEach(line => {
        line = line.trim();
        if (!line || line.startsWith('//')) return;
        const colMatch = line.match(/^["']?([A-Za-z0-9_]+)["']?\s+([A-Za-z0-9_()]+)\s*(?:\[(.*?)\])?/);
        if (colMatch) {
          const colName = colMatch[1];
          if (colName === '_id') return; // Mongoose auto-generates _id
          const colType = colMatch[2].toLowerCase();
          const attrs = (colMatch[3] || '').toLowerCase();

          let typeStr = 'String';
          if (['int', 'integer', 'number', 'decimal', 'float', 'double'].includes(colType)) typeStr = 'Number';
          else if (['boolean', 'bool'].includes(colType)) typeStr = 'Boolean';
          else if (['timestamp', 'date', 'datetime'].includes(colType)) typeStr = 'Date';
          else if (colType === 'objectid') typeStr = 'Schema.Types.ObjectId';
          else if (['json', 'bson', 'object'].includes(colType)) typeStr = 'Schema.Types.Mixed';
          else if (colType.endsWith('[]') || colType === 'array') typeStr = '[Schema.Types.Mixed]';

          // Check for relationship
          const fkRef = refs.find(r => r.fromTable.toLowerCase() === tableName.toLowerCase() && r.fromCol.toLowerCase() === colName.toLowerCase());
          const props: string[] = [];
          if (fkRef) {
            const targetModel = fkRef.toTable.charAt(0).toUpperCase() + fkRef.toTable.slice(1).replace(/s$/, '');
            props.push(`type: Schema.Types.ObjectId, ref: '${targetModel}'`);
          } else {
            props.push(`type: ${typeStr}`);
          }

          if (attrs.includes('not null')) props.push(`required: true`);
          if (attrs.includes('unique')) props.push(`unique: true`);

          fieldLines.push(`  ${colName}: { ${props.join(', ')} }`);
        }
      });

      code += fieldLines.join(',\n');
      code += `\n}, { collection: '${tableName}', timestamps: true });\n\n`;
      code += `const ${modelName} = mongoose.models.${modelName} || mongoose.model('${modelName}', ${modelName}Schema);\n\n`;
    }

    code += `module.exports = { ${modelNames.join(', ')} };\n`;
    return code;
  }
}
